const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),config=require('./config-loader.cjs');
const bases={default:config.primary.url,h3:config.h3.url};
const outputRoots={default:path.resolve(config.primary.outputDir||path.join(config.primary.comfyDir||__dirname,'output')),h3:path.resolve(config.h3.outputDir||path.join(config.h3.runtimeDir||path.join(__dirname,'h3-runtime'),'output'))};
const endpoint=x=>bases[x||'default']||bases.default;
const read=name=>JSON.parse(fs.readFileSync(path.join(__dirname,name),'utf8'));
const catalog=read('hub-catalog.json');
const ledgerPath=path.join(__dirname,'.replica-tools','hub-jobs.json');
let ledger=[];try{ledger=JSON.parse(fs.readFileSync(ledgerPath,'utf8'));}catch{}
function importExistingJobs(q,h){let changed=false;const prompts=[...q.queue_running,...q.queue_pending,...Object.values(h).map(x=>x.prompt)];for(const t of prompts){if(t?.[3]?.client_id!=='yu-production-hub'||ledger.some(x=>x.promptId===t[1]))continue;const nodes=Object.values(t[2]),serialized=JSON.stringify(t[2]);let id=serialized.includes('svd_xt.safetensors')?'svd':serialized.includes('qwen_image_fp8')?'qwen':serialized.includes('sd_xl_base')?'sdxl':null;if(!id&&serialized.includes('flux1-dev-kontext')){const count=nodes.filter(n=>n.class_type==='LoadImage').length;id=count===1?'kontext-one':count===2?'kontext-history':count===3?'kontext-three':null;}const c=catalog.find(c=>c.id===id);if(c){ledger.push({promptId:t[1],workflowId:id,title:c.title,createdAt:h[t[1]]?.status?.messages?.find(m=>m[0]==='execution_start')?.[1]?.timestamp?new Date(h[t[1]].status.messages.find(m=>m[0]==='execution_start')[1].timestamp).toISOString():undefined});changed=true;}}if(changed)saveLedger();}
function saveLedger(){fs.mkdirSync(path.dirname(ledgerPath),{recursive:true});fs.writeFileSync(ledgerPath,JSON.stringify(ledger,null,2));}
function archiveResults(h){let changed=false;for(const r of ledger){const x=h[r.promptId];if(!x)continue;const snapshot={outputs:x.outputs||{},status:x.status};if(JSON.stringify(r.savedResult)!==JSON.stringify(snapshot)){r.savedResult=snapshot;changed=true;}}if(changed)saveLedger();}
let collecting=null;
async function collectJobs(){if(collecting)return collecting;collecting=(async()=>{
 const queue={queue_running:[],queue_pending:[]},history={};let online=false;
 await Promise.all(Object.entries(bases).map(async([backend,base])=>{try{
 const [q,h]=await Promise.all(['/queue','/history?max_items=200'].map(async p=>{const r=await fetch(base+p,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('queue');return r.json();}));
 if(backend==='default')importExistingJobs(q,h);
 for(const entry of Object.values(h))for(const output of Object.values(entry.outputs||{}))for(const values of Object.values(output))if(Array.isArray(values))for(const f of values)if(f?.filename)f.backend=backend;
 Object.assign(history,h);queue.queue_running.push(...q.queue_running);queue.queue_pending.push(...q.queue_pending);online=true;
 }catch{}}));archiveResults(history);for(const r of ledger)if(!history[r.promptId]&&r.savedResult)history[r.promptId]=r.savedResult;
 return {queue,history,records:ledger.filter(r=>!r.hidden),online};})();try{return await collecting;}finally{collecting=null;}}
setInterval(()=>collectJobs().catch(()=>{}),5000).unref();
const caches={};
async function schema(backend='default'){const old=caches[backend];if(old&&Date.now()-old.time<15000)return old.data;const r=await fetch(endpoint(backend)+'/object_info',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('无法读取后台节点');const data=await r.json();caches[backend]={time:Date.now(),data};return data;}
let submitting=false;
async function submit(base,p){if(submitting)throw Error('正在提交其他任务，请稍后重试');submitting=true;try{
 for(const other of Object.values(bases).filter(x=>x!==base)){let q;try{const r=await fetch(other+'/queue',{signal:AbortSignal.timeout(2500)});if(!r.ok)throw Error('无法读取另一个后台的队列');q=await r.json();}catch(e){if(e.cause?.code==='ECONNREFUSED')continue;throw Error('暂时无法确认另一个后台是否空闲，请稍后重试');}
 if(q.queue_running.length||q.queue_pending.length)throw Error('另一个生成引擎还有任务，请等它完成后再提交，避免争抢显存');
 const r=await fetch(other+'/free',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unload_models:true,free_memory:true})});if(!r.ok)throw Error('无法释放空闲引擎显存');}
 return await fetch(base+'/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,client_id:'yu-production-hub'}),signal:AbortSignal.timeout(30000)});
 }finally{submitting=false;}}
function fields(entry,s){const out=[];for(const [id,n] of Object.entries(entry.prompt||{})){const specs={...s[n.class_type]?.input?.required,...s[n.class_type]?.input?.optional};for(const [key,value] of Object.entries(n.inputs)){if(Array.isArray(value))continue;const spec=specs[key];if(!spec)continue;const opts=spec[1]||{};out.push({id,key,node:n.class_type,title:n._meta?.title||n.class_type,value,type:typeof value,options:Array.isArray(spec[0])?spec[0]:Array.isArray(opts.options)?opts.options.map(x=>typeof x==='object'?x.key:x):null,min:opts.min,max:opts.max,step:spec[0]==='INT'?1:opts.step,upload:(n.class_type==='LoadImage'&&key==='image')||(n.class_type==='VHS_LoadVideo'&&key==='video')});}}return out;}
function validate(entry,p,s){const errors=[...entry.issues];if(!p||!Object.keys(p).length)errors.push('没有可提交的 API 工作流');let output=false;for(const [id,n] of Object.entries(p||{})){const def=s[n.class_type];if(!def){errors.push(`节点未加载：${n.class_type}`);continue;}if(def.output_node)output=true;const specs={...def.input?.required,...def.input?.optional};for(const name of Object.keys(def.input?.required||{}))if(!(name in n.inputs))errors.push(`#${id} ${name} 缺少输入`);for(const [key,v] of Object.entries(n.inputs)){const spec=specs[key];if(!spec)continue;if(Array.isArray(v)){const upstream=p[v[0]];if(!upstream||!Number.isInteger(v[1])||!s[upstream.class_type]?.output?.[v[1]])errors.push(`#${id} ${key} 连接无效`);continue;}const type=spec[0],opts=spec[1]||{},isUpload=(n.class_type==='LoadImage'&&key==='image')||(n.class_type==='VHS_LoadVideo'&&key==='video');if(Array.isArray(type)&&!type.includes(v)&&!isUpload)errors.push(`#${id} ${key} 不可用：${String(v).slice(0,160)}`);if(['INT','FLOAT'].includes(type)&&(typeof v!=='number'||!Number.isFinite(v)||(type==='INT'&&!Number.isInteger(v))||v<(opts.min??-Infinity)||v>(opts.max??Infinity)))errors.push(`#${id} ${key} 数值无效`);if(type==='BOOLEAN'&&typeof v!=='boolean')errors.push(`#${id} ${key} 必须为开关值`);if(type==='STRING'&&typeof v!=='string')errors.push(`#${id} ${key} 必须为文本`);}}
if(!output)errors.push('缺少输出节点');return [...new Set(errors)];}
function prepare(entry,changes,s){const p=structuredClone(entry.prompt);const allowed=new Map(fields(entry,s).map(f=>[f.id+':'+f.key,f]));for(const c of changes||[]){const f=allowed.get(c.id+':'+c.key);if(!f)throw Error('不允许修改节点连接或未知参数');if(typeof c.value!==f.type)throw Error('参数类型不匹配');p[c.id].inputs[c.key]=c.value;}return p;}
async function body(req){let size=0,a=[];for await(const b of req){size+=b.length;if(size>150*1024*1024)throw Error('上传超过 150MB');a.push(b);}return Buffer.concat(a);}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function handle(req,res){const u=new URL(req.url,'http://127.0.0.1');if(!u.pathname.startsWith('/hub-api/'))return false;
try{const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`)return json(res,403,{error:'跨站请求已拒绝'}),true;
if(req.method==='GET'&&u.pathname==='/hub-api/catalog'){
 const ready=await require('./h3-runtime.cjs').ensure();
 const schemas={};let online=false;await Promise.all(Object.keys(bases).map(async k=>{try{schemas[k]=await schema(k);online=true;}catch{schemas[k]=k==='h3'?read('hub-schema-h3.json'):read('hub-schema.json');}}));
 json(res,200,{online,error:'生成引擎未连接',entries:catalog.map(c=>({...c,prompt:undefined,graph:undefined,fields:fields(c,schemas[c.backend||'default']),problems:validate(c,c.prompt,schemas[c.backend||'default']),runtimeMessage:c.backend==='h3'&&!ready.ready?ready.message:undefined}))});}
else if(req.method==='GET'&&u.pathname==='/hub-api/workflow'){const c=catalog.find(c=>c.id===u.searchParams.get('id'));if(!c)throw Error('工作流不存在');json(res,200,{graph:c.graph,prompt:c.prompt});}
else if(req.method==='POST'&&['/hub-api/check','/hub-api/run'].includes(u.pathname)){if(!req.headers['content-type']?.includes('application/json'))throw Error('需要 JSON');const b=JSON.parse((await body(req)).toString());const c=catalog.find(c=>c.id===b.id);if(!c)throw Error('工作流不存在');const base=endpoint(c.backend);const s=await schema(c.backend),p=prepare(c,b.changes,s),errors=validate(c,p,s);if(c.backend==='h3'){const x=p['4'].inputs;if(x.width%32||x.height%32)errors.push('H3 宽高需为 32 的倍数');if(x.length%17!==5)errors.push('H3 帧数请使用 124、141、158 等 17k+5 数值');}if(errors.length)json(res,422,{errors});else if(u.pathname.endsWith('/check'))json(res,200,{ok:true,message:'节点、模型选项和参数检查通过；未执行生成'});else{const r=await submit(base,p);const result=await r.json();if(r.ok&&result.prompt_id){ledger.push({promptId:result.prompt_id,workflowId:c.id,backend:c.backend||'default',title:c.title,createdAt:new Date().toISOString()});try{saveLedger();}catch(e){result.persistenceWarning='任务已提交，但历史索引保存失败';}}json(res,r.status,result);}}
else if(req.method==='POST'&&u.pathname==='/hub-api/upload'){const base=endpoint(catalog.find(c=>c.id===u.searchParams.get('id'))?.backend);const name=path.basename(u.searchParams.get('name')||'');if(!/\.(png|jpe?g|webp|mp4|webm|mov)$/i.test(name))throw Error('请选择图片或视频文件');const data=await body(req),form=new FormData();form.set('image',new Blob([data]),'yu_'+Date.now()+'_'+name);form.set('type','input');form.set('overwrite','false');const r=await fetch(base+'/upload/image',{method:'POST',body:form,signal:AbortSignal.timeout(60000)});for(const k of Object.keys(caches))delete caches[k];json(res,r.status,await r.json());}
else if(req.method==='GET'&&u.pathname==='/hub-api/jobs'){json(res,200,await collectJobs());}
else if(req.method==='POST'&&u.pathname==='/hub-api/hide'){const b=JSON.parse((await body(req)).toString());let record=ledger.find(x=>x.promptId===b.promptId);if(!record){record={promptId:b.promptId,hidden:true,createdAt:new Date().toISOString()};ledger.push(record);}else record.hidden=true;saveLedger();json(res,200,{ok:true,message:'已从列表删除，硬盘文件未删除'});}
else if(req.method==='POST'&&u.pathname==='/hub-api/open-folder'){const b=JSON.parse((await body(req)).toString());const jobs=await collectJobs(),record=ledger.find(x=>x.promptId===b.promptId)||{promptId:b.promptId},history=jobs.history[record.promptId],detected=Object.values(history?.outputs||{}).flatMap(x=>Object.values(x).filter(Array.isArray).flat()).find(f=>f?.backend)?.backend,root=outputRoots[record.backend||detected||'default'];let target=root,select=false;for(const output of Object.values(history?.outputs||{})){for(const values of Object.values(output))if(Array.isArray(values))for(const f of values){if(!f?.filename||f.type!=='output')continue;const candidate=path.resolve(root,f.subfolder||'',f.filename);if((candidate===root||candidate.startsWith(root+path.sep))&&fs.existsSync(candidate)){target=candidate;select=true;break;}}if(select)break;}if(!fs.existsSync(root))throw Error('输出目录不存在，请在 config.local.json 设置 outputDir');let command,args;if(process.platform==='win32'){command='explorer.exe';args=[select?'/select,'+target:target];}else if(process.platform==='darwin'){command='open';args=select?['-R',target]:[target];}else{command='xdg-open';args=[select?path.dirname(target):target];}const child=spawn(command,args,{detached:true,stdio:'ignore'});child.unref();json(res,200,{ok:true,message:select?'已打开并选中文件':'已打开输出文件夹'});}
else if(req.method==='POST'&&u.pathname==='/hub-api/cancel'){const b=JSON.parse((await body(req)).toString());const record=ledger.find(x=>x.promptId===b.promptId);if(!record)throw Error('任务不属于此 Hub');const base=endpoint(record.backend);const q=await(await fetch(base+'/queue')).json();if(!q.queue_pending.some(x=>x[1]===b.promptId))return json(res,409,{error:'任务已开始或已结束，不能取消等待'}),true;const r=await fetch(base+'/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({delete:[b.promptId]})});if(!r.ok)throw Error('取消失败');record.cancelled=true;saveLedger();json(res,200,{ok:true});}
else if(req.method==='GET'&&u.pathname==='/hub-api/media'){const base=endpoint(u.searchParams.get('backend'));u.searchParams.delete('backend');const r=await fetch(base+'/view?'+u.searchParams,{signal:AbortSignal.timeout(30000)});res.writeHead(r.status,{'Content-Type':r.headers.get('content-type')||'application/octet-stream'});res.end(Buffer.from(await r.arrayBuffer()));}
else json(res,404,{error:'接口不存在'});
}catch(e){json(res,503,{error:e.message});}return true;}
module.exports={handle,validate,prepare,fields,catalog};
