'use strict';
let entries=[],selected=null,online=false,filter='全部',timer=null,view=0;
const drafts=new Map(),$=s=>document.querySelector(s),el=(t,text,cls)=>{const e=document.createElement(t);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const names={prompt:'提示词',length:'视频帧数（124 帧约 5 秒）',noise_seed:'随机种子',seed:'随机种子',steps:'采样步数',cfg:'CFG 引导',sampler_name:'采样器',scheduler:'调度器',denoise:'降噪强度',width:'宽度',height:'高度',batch_size:'单次张数',filename_prefix:'输出文件名前缀',fps:'帧率',video_frames:'视频帧数',ckpt_name:'主模型',unet_name:'扩散模型',clip_name:'文本编码器',vae_name:'VAE',guidance:'引导强度',motion_bucket_id:'运动幅度',augmentation_level:'参考图扰动'};
const descriptions={qwen:'用文字描述画面，生成中文创意配图。','kontext-history':'上传两张图片，描述如何组合或修改。','kontext-one':'上传一张图片，通过文字修改背景、风格或细节。','kontext-three':'上传三张图片，描述各张图片在成品中的作用。',sdxl:'输入画面描述，生成一张新的图片。',svd:'上传图片后自动匹配画幅，生成约 4 秒短动画。原图中的字幕可能变化，建议后期添加。'};
async function api(url,opt){const r=await fetch(url,opt),j=await r.json();if(!r.ok)throw Error(j.errors?.join('\n')||j.error?.message||j.error||JSON.stringify(j));return j;}
function media(f){return '/hub-api/media?'+new URLSearchParams({filename:f.filename,subfolder:f.subfolder||'',type:f.type||'output',backend:f.backend||'default'});}
function draft(c){if(!drafts.has(c.id)){let job=null;try{job=localStorage.getItem('yu-last-job-'+c.id);}catch{}drafts.set(c.id,{values:Object.fromEntries(c.fields.map(f=>[f.id+':'+f.key,f.upload?'':f.value])),slots:{},pending:0,busy:false,job,result:[],index:0,message:''});}return drafts.get(c.id);}
function changes(c){return c.fields.map(f=>({id:f.id,key:f.key,value:draft(c).values[f.id+':'+f.key]}));}
function negative(c,f){return ['text','prompt'].includes(f.key)&&((c.id==='qwen'&&f.id==='7')||(c.id==='sdxl'&&f.id==='3')||(f.node==='CLIPTextEncode'&&!String(f.value).trim()));}
function updateFilters(){for(const b of document.querySelectorAll('[data-filter]')){const key=b.dataset.filter,count=key==='全部'?entries.length:entries.filter(c=>c.kind===key).length;b.textContent=`${b.dataset.label||key} ${count}`;b.hidden=count===0;}}
function cards(){const box=$('#cards');box.replaceChildren();for(const c of entries.filter(c=>filter==='全部'||c.kind===filter)){const b=el('button',undefined,'card'+(c.id===selected?' selected':''));b.setAttribute('aria-pressed',String(c.id===selected));b.append(el('h3',c.title),el('span',c.evidence,'badge good'));b.onclick=()=>{show(c.id);$('#panel').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};box.append(b);}}
function sync(c){if(selected!==c.id)return;const d=draft(c),run=$('#generate-btn');if(!run)return;const missing=c.fields.some(f=>f.upload&&!d.slots[f.id+':'+f.key]);run.disabled=!online||d.pending>0||d.batchUploading||d.submitting||missing;run.textContent=d.pending?'上传中…':d.submitting?'提交中…':d.busy?'继续加入队列':'加入生成队列';$('#clear-btn').disabled=!!d.pending||!!d.batchUploading||!!d.submitting;$('#message').textContent=d.message;$('#upload-note').textContent=missing?'请先上传所有参考素材。':'';}
function field(c,f,advanced=false){const d=draft(c),key=f.id+':'+f.key,l=el('label',undefined,'field');l.append(el('span',(c.id==='qwen-original-six'?'第 '+(Math.floor((Number(f.id)-1)/12)+1)+' 路 · ':'')+(['text','prompt'].includes(f.key)?(negative(c,f)?'反向提示词':'提示词'):f.key==='fps'?(f.node==='SVD_img2vid_Conditioning'?'运动参考帧率':'播放帧率'):names[f.key]||f.key),'caption'));if(advanced)l.append(el('small',f.title+' · #'+f.id,'node-hint'));let i;
if(f.options){i=el('select');const opts=[...f.options];if(!opts.includes(d.values[key]))opts.unshift(d.values[key]);opts.forEach(v=>{const o=el('option',String(v));o.value=String(v);i.append(o);});i.value=d.values[key];}
else if(f.type==='boolean'){i=el('input');i.type='checkbox';i.checked=d.values[key];}
else if(f.type==='number'){i=el('input');i.type='number';i.value=d.values[key];if(f.min!==undefined)i.min=f.min;if(f.max!==undefined)i.max=Math.min(f.max,Number.MAX_SAFE_INTEGER);i.step=f.step||'any';}
else{i=el(['text','prompt'].includes(f.key)||String(f.value).length>130?'textarea':'input');i.value=d.values[key]??'';if(['text','prompt'].includes(f.key)){i.placeholder='描述你希望生成或修改的画面…';i.rows=5;}}
i.dataset.field=key;i.oninput=()=>{d.values[key]=f.type==='boolean'?i.checked:f.type==='number'?(i.value===''?NaN:Number(i.value)):i.value;sync(c);};l.append(i);return l;}
function slot(c,f,index){const d=draft(c),key=f.id+':'+f.key,w=el('div',undefined,'upload-slot'),isVideo=f.key==='video',title=(isVideo?'视频':'图片')+' '+String.fromCharCode(65+index);w.append(el('div',title,'caption'));const b=el('button',undefined,'dropzone'),input=el('input'),name=el('div','','upload-name');b.type='button';b.setAttribute('aria-label','上传'+title);input.type='file';input.accept=isVideo?'video/mp4,video/webm,video/quicktime':'image/png,image/jpeg,image/webp';input.hidden=true;if(c.batchUpload)input.multiple=true;
function render(){b.replaceChildren();const s=d.slots[key];if(s){const img=el(isVideo?'video':'img');img.src=s.url;img.alt='参考'+title;if(isVideo)img.muted=true;b.append(img,el('span','点击替换','replace-hint'));name.textContent=s.name;}else{b.append(el('span','＋','upload-symbol'),el('strong','点击选择'+title),el('span','或拖拽文件到这里','muted'));name.textContent=c.batchUpload?'可多选图片，每张分别加入队列':isVideo?'MP4 / WebM / MOV · 最大 150MB':'PNG / JPG / WebP · 最大 150MB';}}
async function upload(file){if(!file)return;const valid=isVideo?/\.(mp4|webm|mov)$/i:/\.(png|jpe?g|webp)$/i;if(!valid.test(file.name)||file.size>150*1024*1024){d.message='请选择支持格式且小于 150MB 的文件。';sync(c);return;}d.pending++;b.disabled=true;name.textContent='正在上传…';sync(c);try{const r=await api('/hub-api/upload?name='+encodeURIComponent(file.name)+'&id='+encodeURIComponent(c.id),{method:'POST',body:file});if(d.slots[key])URL.revokeObjectURL(d.slots[key].url);d.slots[key]={name:file.name,url:URL.createObjectURL(file)};d.values[key]=(r.subfolder?r.subfolder+'/':'')+r.name;d.message='素材已准备好。';if((c.id==='svd'||c.id==='h3-image')&&!isVideo){await new Promise((resolve,reject)=>{const probe=new Image();probe.onload=()=>{const unit=c.backend==='h3'?32:8,edge=c.backend==='h3'?512:1024;const scale=Math.min(edge/Math.max(probe.naturalWidth,probe.naturalHeight),Math.sqrt(589824/(probe.naturalWidth*probe.naturalHeight))),width=Math.max(64,Math.round(probe.naturalWidth*scale/unit)*unit),height=Math.max(64,Math.round(probe.naturalHeight*scale/unit)*unit);for(const [name,value] of [['width',width],['height',height]]){const f=c.fields.find(f=>f.key===name);if(f){d.values[f.id+':'+f.key]=value;if(selected===c.id){const input=document.querySelector('[data-field="'+f.id+':'+f.key+'"]');if(input)input.value=value;}}}d.message='已按原图匹配 '+width+'×'+height+'，保留完整画面。';sync(c);resolve();};probe.onerror=()=>reject(Error('无法读取图片尺寸'));probe.src=d.slots[key].url;});}}catch(e){d.message='上传失败：'+e.message;}finally{d.pending--;b.disabled=false;render();sync(c);}}
async function uploadSelection(files){if(!c.batchUpload)return upload(files[0]);d.batchUploading=true;d.batchFiles=[];if(d.slots[key])URL.revokeObjectURL(d.slots[key].url);delete d.slots[key];d.values[key]="";sync(c);try{for(const file of files){const before=d.values[key];await upload(file);if(d.values[key]!==before)d.batchFiles.push({name:file.name,image:d.values[key]});}d.message=d.batchFiles.length+' 张图片已准备好，将分别加入生成队列。';name.textContent=d.batchFiles.length+' 张图片 · '+d.batchFiles.map(x=>x.name).join('、');}finally{d.batchUploading=false;sync(c);}}
b.onclick=()=>input.click();input.onchange=()=>uploadSelection([...input.files]);b.ondragover=e=>{e.preventDefault();b.classList.add('dragover');};b.ondragleave=()=>b.classList.remove('dragover');b.ondrop=e=>{e.preventDefault();b.classList.remove('dragover');if(!b.disabled)uploadSelection([...e.dataTransfer.files]);};render();w.append(b,input,name);return w;}
function reset(c){const d=draft(c);if(d.pending||d.submitting)return;Object.values(d.slots).forEach(s=>URL.revokeObjectURL(s.url));drafts.delete(c.id);show(c.id);}
function show(id){clearTimeout(timer);view++;selected=id;cards();const c=entries.find(e=>e.id===id),d=draft(c),p=$('#panel');p.replaceChildren();const head=el('div',undefined,'workspace-head');head.append(el('div',c.kind==='视频'?'VIDEO STUDIO':'IMAGE STUDIO','eyebrow'),el('h2',c.title),el('p',descriptions[id]||c.description));p.append(head);const grid=el('div',undefined,'workflow-grid'),left=el('section',undefined,'io-panel input-panel'),right=el('section',undefined,'io-panel output-panel');left.setAttribute('aria-label','输入与参数');right.setAttribute('aria-label','生成结果');grid.append(left,right);p.append(grid);let step=1;
const uploads=c.fields.filter(f=>f.upload),positives=c.fields.filter(f=>['text','prompt'].includes(f.key)&&!negative(c,f)),size=c.fields.filter(f=>['width','height'].includes(f.key)),simple=c.fields.filter(f=>['video_frames','fps','batch_size','motion_bucket_id',...(c.backend==='h3'?['length','steps']:[]),...(c.id.startsWith('kontext')?['steps','guidance','cfg','denoise']:[])].includes(f.key));
if(uploads.length){left.append(el('h3',`${step++}. 上传参考素材`,'section-label'));const slots=el('div',undefined,'upload-grid slots-'+uploads.length);uploads.forEach((f,i)=>slots.append(slot(c,f,i)));left.append(slots);}
if(positives.length){left.append(el('h3',`${step++}. ${uploads.length?'描述修改效果':'描述想要的画面'}`,'section-label'));positives.forEach(f=>left.append(field(c,f)));}
if(size.length||simple.length){left.append(el('h3',`${step++}. 尺寸与输出`,'section-label'));if(size.length===2){const row=el('div',undefined,'ratio-row'),w=size.find(f=>f.key==='width'),h=size.find(f=>f.key==='height');const presets=c.backend==='h3'?[['横屏 16:9',512,288],['竖屏 9:16',288,512],['方形 1:1',384,384]]:c.kind==='视频'?[['横屏 16:9',1024,576],['竖屏 9:16',576,1024],['方形 1:1',768,768]]:[['方形 1:1',768,768],['竖屏 2:3',768,1152],['横屏 3:2',1152,768]];for(const [title,width,height] of presets){const b=el('button',title);b.onclick=()=>{for(const [f,v] of [[w,width],[h,height]]){d.values[f.id+':'+f.key]=v;left.querySelector('[data-field="'+f.id+':'+f.key+'"]').value=v;}};row.append(b);}left.append(row);}const dimensions=el('div',undefined,'fields');[...size,...simple].forEach(f=>dimensions.append(field(c,f)));left.append(dimensions);}else if(uploads.length)left.append(el('p','输出尺寸按原工作流随参考图片调整。','muted'));
const used=new Set([...uploads,...positives,...size,...simple].map(f=>f.id+':'+f.key)),advanced=el('details',undefined,'advanced'),fields=el('div',undefined,'fields');advanced.append(el('summary','高级设置 · 原工作流完整参数'));c.fields.filter(f=>!used.has(f.id+':'+f.key)).forEach(f=>fields.append(field(c,f,true)));advanced.append(fields);const tools=el('div',undefined,'secondary-actions'),check=el('button','检查参数'),exportBtn=el('button','导出参数');tools.append(check,exportBtn);advanced.append(tools);left.append(advanced);
const actions=el('div',undefined,'generate-row'),clear=el('button','清空 / 恢复默认'),run=el('button','生成','primary');run.id='generate-btn';clear.id='clear-btn';clear.onclick=()=>reset(c);actions.append(clear,run);const note=el('div','','muted');note.id='upload-note';const msg=el('div',d.message,'toast');msg.id='message';msg.setAttribute('role','status');left.append(actions,note,msg);
right.append(el('h3','生成结果','section-label'));const result=el('div',undefined,'result-box');result.id='result';result.setAttribute('aria-live','polite');right.append(result);const downloads=el('div',undefined,'download-row'),download=el('button','下载到本地'),collect=el('button','保存到本机作品集');download.id='download-result';collect.id='collect-result';downloads.append(download,collect);right.append(downloads,el('p','作品仅保存在本机，不会公开发布。','muted'));download.onclick=()=>downloadFile(d.result[d.index]);collect.onclick=()=>collectFile(c,d.result[d.index]);const proof=el('details');proof.append(el('summary','工作流运行说明'),el('p',c.description));right.append(proof);const gallery=el('section',undefined,'gallery-section');gallery.append(el('h3','本机作品集'),el('p','保存满意的作品，随时查看和下载。','muted'));const items=el('div',undefined,'gallery-grid');items.id='gallery';gallery.append(items);p.append(gallery);renderGallery();renderResult(c);sync(c);
check.onclick=async()=>{try{const r=await api('/hub-api/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,changes:changes(c)})});d.message=r.message;}catch(e){d.message=e.message;}sync(c);};exportBtn.onclick=async()=>{try{const w=await api('/hub-api/workflow?id='+id);changes(c).forEach(v=>w.prompt[v.id].inputs[v.key]=v.value);const url=URL.createObjectURL(new Blob([JSON.stringify(w.prompt,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=id+'-api.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){d.message=e.message;sync(c);}};
run.onclick=async()=>{if(run.disabled)return;d.submitting=true;d.busy=true;d.result=[];d.message='正在提交任务…';sync(c);renderResult(c);try{const batches=c.batchUpload&&d.batchFiles?.length?d.batchFiles:[null];let submitted=0;for(const item of batches){const values=changes(c);if(item){const target=c.fields.find(f=>f.upload);values.find(v=>v.id===target.id&&v.key===target.key).value=item.image;}const r=await api('/hub-api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,changes:values})});d.job=r.prompt_id;submitted++;d.message='已提交 '+submitted+' / '+batches.length+' 项任务';sync(c);try{localStorage.setItem('yu-last-job-'+id,d.job);}catch{}}d.message=submitted+' 项已加入队列，完成后自动进入资产库。';refreshQueue();watch(d.job,id,view);}catch(e){d.busy=false;d.message='提交失败：'+e.message;renderResult(c);}finally{d.submitting=false;}sync(c);};if(d.job)watch(d.job,id,view);
}
function renderResult(c){if(selected!==c.id)return;const d=draft(c),box=$('#result'),file=d.result[d.index];box.replaceChildren();$('#download-result').disabled=!file;$('#collect-result').disabled=!file;if(!file){box.className='result-box'+(d.busy?' loading':'');box.append(el('span',d.busy?'◌':'◇','result-symbol'),el('strong',d.busy?'正在为你生成作品':'等待你的创作'),el('p',d.busy?'完成后会自动显示在这里':c.kind==='视频'?'生成的短动画将显示在这里':'生成的图片将显示在这里'));return;}box.className='result-box done';const video=/\.(mp4|webm|mov)$/i.test(file.filename),img=el(video?'video':'img');img.src=media(file);if(video)img.controls=true;else img.alt='生成结果';box.append(img);if(d.result.length>1){const nav=el('div',undefined,'result-nav');d.result.forEach((f,i)=>{const b=el('button',String(i+1),i===d.index?'active':'');b.setAttribute('aria-label','查看结果 '+(i+1));b.onclick=()=>{d.index=i;renderResult(c);};nav.append(b);});box.append(nav);}box.append(el('div',file.filename,'upload-name'));}
function downloadFile(f){if(!f)return;const a=el('a');a.href=media(f);a.download=f.filename;a.click();}
function portfolio(){try{return JSON.parse(localStorage.getItem('yu-portfolio-v1'))||[];}catch{return [];}}
function collectFile(c,f){if(!f)return;const items=portfolio();if(!items.some(x=>media(x.file)===media(f)))items.unshift({file:f,title:c.title,date:new Date().toISOString()});try{localStorage.setItem('yu-portfolio-v1',JSON.stringify(items.slice(0,100)));draft(c).message='已保存到本机作品集。';}catch{draft(c).message='浏览器存储不可用，请下载到本地保存。';}sync(c);renderGallery();}
function renderGallery(){const box=$('#gallery');if(!box)return;box.replaceChildren();const items=portfolio();if(!items.length){box.append(el('p','暂无作品。生成后点击“保存到本机作品集”。','empty'));return;}for(const item of items){const card=el('article',undefined,'gallery-card'),a=el('a');a.href=media(item.file);a.target='_blank';a.rel='noopener';const video=/\.(mp4|webm|mov)$/i.test(item.file.filename),img=el(video?'video':'img');img.src=a.href;if(video){img.muted=true;img.preload='metadata';}else{img.alt=item.title;img.loading='lazy';}a.append(img);const download=el('button','下载');download.onclick=()=>downloadFile(item.file);card.append(a,el('strong',item.title),el('p',new Date(item.date).toLocaleString(),'muted'),download);box.append(card);}}
async function watch(job,id,token){if(selected!==id||token!==view)return;const c=entries.find(e=>e.id===id),d=draft(c);try{const j=await api('/hub-api/jobs');if(selected!==id||token!==view||d.job!==job)return;const h=j.history[job];if(h){d.busy=false;if(h.status?.status_str==='error')d.message='生成失败：'+JSON.stringify(h.status.messages.filter(x=>x[0]==='execution_error').map(x=>x[1].exception_message||x[1].exception_type));else{const files=[];for(const o of Object.values(h.outputs||{}))for(const values of Object.values(o)){if(!Array.isArray(values))continue;for(const f of values)if(f?.filename&&f.type==='output'&&/\.(png|jpe?g|webp|gif|mp4|webm|mov)$/i.test(f.filename)&&!files.some(x=>media(x)===media(f)))files.push(f);}d.result=files;d.index=0;d.message=files.length?'生成完成，可以预览和下载。':'任务结束，没有可预览的输出文件。';}sync(c);renderResult(c);return;}const running=(j.queue.queue_running||[]).some(x=>x[1]===job),waiting=(j.queue.queue_pending||[]).some(x=>x[1]===job);d.busy=running||waiting;d.message=running?'正在后台生成…':waiting?'任务排队中…':'未找到上次任务记录，已生成文件仍在本机 output 目录。';sync(c);renderResult(c);if(!d.busy)return;}catch(e){if(selected!==id||token!==view)return;d.message='读取生成状态失败，正在重试…';sync(c);}timer=setTimeout(()=>watch(job,id,token),4000);}
async function load(){try{const j=await api('/hub-api/catalog');entries=j.entries.filter(c=>!c.problems.length);online=j.online;$('#connection').textContent=online?'● 生成引擎已就绪':'○ '+j.error;$('#count').textContent=entries.length;updateFilters();if(entries.length)show(entries.some(c=>c.id===selected)?selected:entries[0].id);else $('#panel').replaceChildren(el('p','暂时没有可用工作流，请等待后台启动后重新检查。'));}catch(e){$('#connection').textContent='连接失败：'+e.message;}}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));cards();});$('#refresh').onclick=boot;
async function boot(){try{const r=await api('/hub-api/runtime');if(!r.ready){$('#connection').textContent=r.message;setTimeout(boot,5000);return;}await load();}catch(e){$('#connection').textContent='后台连接失败：'+e.message;}}boot();

// Shared task drawer: ComfyUI executes queued jobs serially on this GPU.
let queueSnapshot=null,queueFilter='all',queueRenderKey='';
const queueToggle=el('button','任务队列','queue-toggle');queueToggle.id='queue-toggle';
const drawer=el('aside',undefined,'queue-drawer');drawer.id='queue-drawer';drawer.hidden=!matchMedia('(min-width:1200px)').matches;drawer.setAttribute('aria-label','生成任务队列');
const queueHead=el('div',undefined,'queue-head'),queueClose=el('button','收起');queueHead.append(el('h3','生成队列'),queueClose);
const allTab=el('button','全部任务','active');
const queueSummary=el('p','正在读取任务…','muted'),queueTabs=el('div',undefined,'queue-tabs'),waitingTab=el('button','等待 / 生成中','active'),historyTab=el('button','历史结果'),queueList=el('div',undefined,'queue-list');
queueTabs.append(allTab,waitingTab,historyTab);drawer.append(queueHead,queueSummary,queueTabs,queueList);document.body.append(queueToggle,drawer);
const quickNav=el('nav',undefined,'quick-nav');quickNav.setAttribute('aria-label','结果与任务入口');
const assetsButton=el('button','资产库'),studioButton=el('button','返回创作');
const currentResult=el('button','当前结果'),allResults=el('button','历史结果 / 下载'),queueEntry=el('button','生成队列');
quickNav.append(studioButton,assetsButton,currentResult,allResults,queueEntry);document.querySelector('header').after(quickNav);
currentResult.onclick=()=>{openStudio();$('.output-panel')?.scrollIntoView({block:'start'});};
function openQueue(tab){queueFilter=tab;drawer.hidden=false;queueToggle.setAttribute('aria-expanded','true');drawQueue();refreshQueue();}
allResults.onclick=()=>openQueue('history');queueEntry.onclick=()=>openQueue('all');

queueToggle.onclick=()=>{drawer.hidden=!drawer.hidden;queueToggle.setAttribute('aria-expanded',String(!drawer.hidden));refreshQueue();};queueClose.onclick=()=>{drawer.hidden=true;queueToggle.setAttribute('aria-expanded','false');};
allTab.onclick=()=>{queueFilter='all';drawQueue();};
waitingTab.onclick=()=>{queueFilter='waiting';drawQueue();};historyTab.onclick=()=>{queueFilter='history';drawQueue();};
function drawQueue(){if(!queueSnapshot)return;const j=queueSnapshot,waiting=[...(j.queue.queue_pending||[])].sort((a,b)=>a[0]-b[0]),running=j.queue.queue_running||[],records=[...(j.records||[])];
for(const c of entries){let id;try{id=localStorage.getItem('yu-last-job-'+c.id);}catch{}if(id&&!records.some(r=>r.promptId===id))records.push({promptId:id,workflowId:c.id,title:c.title});}
for(const task of [...running,...waiting])if(!records.some(r=>r.promptId===task[1]))records.push({promptId:task[1],title:'其他后台任务',workflowId:null});
queueToggle.textContent='任务队列 · '+running.length+' 生成中 / '+waiting.length+' 等待';queueSummary.textContent='后台逐个生成，可继续提交。'+running.length+' 项生成中，'+waiting.length+' 项等待。';allTab.classList.toggle('active',queueFilter==='all');waitingTab.classList.toggle('active',queueFilter==='waiting');historyTab.classList.toggle('active',queueFilter==='history');const key=JSON.stringify([queueFilter,records.map(r=>[r.promptId,r.cancelled]),running.map(x=>x[1]),waiting.map(x=>x[1]),Object.entries(j.history).map(([id,h])=>[id,h.status?.status_str])]);if(key===queueRenderKey)return;queueRenderKey=key;queueList.replaceChildren();let count=0;
for(const r of [...records].sort((a,b)=>Date.parse(b.createdAt||0)-Date.parse(a.createdAt||0))){const history=j.history[r.promptId],isRunning=running.some(x=>x[1]===r.promptId),position=waiting.findIndex(x=>x[1]===r.promptId),active=isRunning||position>=0;if(queueFilter!=='all'&&(queueFilter==='waiting')!==active)continue;count++;const card=el('article',undefined,'queue-item');let status=isRunning?'正在生成':position>=0?'等待 · 第 '+(position+1)+' 位':history?.status?.status_str==='error'?'生成失败':history?'已完成':r.cancelled?'已取消':'记录已失效';const outputFiles=Object.values(history?.outputs||{}).flatMap(o=>Object.values(o).filter(Array.isArray).flat()).filter(f=>f?.filename&&f.type==='output');const preview=outputFiles.find(f=>/\.(png|jpe?g|webp)$/i.test(f.filename));if(preview){const thumbnail=el('img');thumbnail.src=media(preview);thumbnail.alt=r.title+'生成结果缩略图';thumbnail.loading='lazy';thumbnail.className='queue-thumb';card.append(thumbnail);}card.append(el('strong',r.title),el('span',status,'badge'+(history&&history.status?.status_str!=='error'?' good':'')));if(r.createdAt)card.append(el('p',new Date(r.createdAt).toLocaleString(),'muted'));const open=el('button',history?'查看结果':'查看任务');open.onclick=()=>{const c=entries.find(c=>c.id===r.workflowId);if(!c)return;openStudio();draft(c).job=r.promptId;show(c.id);drawer.hidden=!matchMedia('(min-width:1200px)').matches;queueToggle.setAttribute('aria-expanded',String(!drawer.hidden));$('.output-panel').scrollIntoView({block:'start'});};if(r.workflowId)card.append(open);
if(position>=0&&(j.records||[]).some(x=>x.promptId===r.promptId)){const cancel=el('button','取消等待');cancel.onclick=async()=>{cancel.disabled=true;try{await api('/hub-api/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({promptId:r.promptId})});await refreshQueue();}catch(e){queueSummary.textContent=e.message;cancel.disabled=false;}};card.append(cancel);}queueList.append(card);}
if(!count)queueList.append(el('p',queueFilter==='waiting'?'此 Hub 暂无待生成任务。':'暂无历史结果。','empty'));}
async function refreshQueue(){try{queueSnapshot=await api('/hub-api/jobs');drawQueue();renderAssets();}catch(e){queueSummary.textContent='暂时无法读取队列，稍后自动重试。';}}
refreshQueue();setInterval(refreshQueue,4000);

// Persistent generated assets are indexed by the local server, not browser storage.
const assetPage=el('section',undefined,'asset-page');assetPage.hidden=true;assetPage.setAttribute('aria-label','资产库');
assetPage.append(el('h1','资产库'),el('p','生成完成的作品自动收录。点击作品预览、下载；队列中的已完成记录也会保留。'));
const assetCount=el('p','','muted'),assetGrid=el('div',undefined,'asset-grid');assetPage.append(assetCount,assetGrid);document.querySelector('main').after(assetPage);
const previewDialog=el('dialog',undefined,'asset-preview'),previewClose=el('button','关闭预览'),previewTitle=el('h2'),previewBody=el('div'),previewDownload=el('button','下载作品');previewDialog.append(previewClose,previewTitle,previewBody,previewDownload);document.body.append(previewDialog);previewClose.onclick=()=>previewDialog.close();
function openStudio(){assetPage.hidden=true;document.querySelector('main').hidden=false;assetsButton.classList.remove('active');}
studioButton.onclick=openStudio;
assetsButton.onclick=()=>{document.querySelector('main').hidden=true;assetPage.hidden=false;assetsButton.classList.add('active');drawer.hidden=true;queueToggle.setAttribute('aria-expanded','false');renderAssets();assetPage.scrollIntoView({block:'start'});refreshQueue();};
function previewAsset(r,f){previewTitle.textContent=r.title;previewBody.replaceChildren();const video=/\.(mp4|webm|mov)$/i.test(f.filename),m=el(video?'video':'img');m.src=media(f);if(video)m.controls=true;else m.alt=r.title+'作品预览';previewBody.append(m,el('p',f.filename));previewDownload.onclick=()=>downloadFile(f);previewDialog.showModal();}
let assetSignature='';
function renderAssets(){if(!queueSnapshot)return;const items=[];for(const r of [...(queueSnapshot.records||[])].reverse()){const h=queueSnapshot.history[r.promptId];if(!h||h.status?.status_str==='error')continue;for(const o of Object.values(h.outputs||{}))for(const v of Object.values(o))if(Array.isArray(v))for(const f of v)if(f?.filename&&f.type==='output'&&/\.(png|jpe?g|webp|gif|mp4|webm|mov)$/i.test(f.filename)&&!items.some(x=>media(x.f)===media(f)))items.push({r,f});}const sig=JSON.stringify(items.map(x=>[x.r.promptId,media(x.f)]));if(sig===assetSignature)return;assetSignature=sig;assetGrid.replaceChildren();assetCount.textContent=items.length+' 件作品 · 保存在本机';if(!items.length)assetGrid.append(el('p','暂无作品，生成完成后会自动出现在这里。'));for(const {r,f} of items){const card=el('article',undefined,'asset-card'),open=el('button',undefined,'asset-open');open.setAttribute('aria-label','预览 '+f.filename);const video=/\.(mp4|webm|mov)$/i.test(f.filename),m=el(video?'video':'img');m.src=media(f);if(video){m.muted=true;m.preload='metadata';}else{m.alt=r.title;m.loading='lazy';}open.append(m);open.onclick=()=>previewAsset(r,f);const download=el('button','下载');download.onclick=()=>downloadFile(f);card.append(open,el('h3',r.title),el('span','已完成','badge good'),el('p',f.filename,'muted'),download);assetGrid.append(card);}}
